name: final_project
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter_staggered_grid_view: ^0.7.0
  firebase_core: ^2.15.1
  firebase_crashlytics: ^3.3.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  lottie: ^2.6.0
  smooth_page_indicator: ^1.1.0
  supabase_flutter: ^1.10.14
  cached_network_image: ^3.2.3
  get_storage: ^2.1.1  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/
